# Generated by Django 5.2.4 on 2025-08-14 14:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicecategory",
            old_name="name",
            new_name="service",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="constomer",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="category",
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="worker",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="experience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="worker_image/"),
        ),
        migrations.AddField(
            model_name="worker",
            name="location",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="profession",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="HomeApp.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.", regex="^\\+?\\d{7,15}$"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_image/"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
