# Generated by Django 5.2.4 on 2025-08-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workerservice",
            old_name="service",
            new_name="services",
        ),
    ]
