# Generated by Django 5.2.4 on 2025-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerrating",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
