# Generated by Django 5.2.4 on 2025-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0002_rename_service_workerservice_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerservice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
