# Generated by Django 5.2.4 on 2025-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0003_workerservice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="worker",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
