# Generated by Django 5.2.4 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_booking_amount_booking_pay_later_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('due', 'Due'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
    ]
