# Generated by Django 5.2.4 on 2025-09-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0005_workerrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="name",
            new_name="username",
        ),
    ]
