# Generated by Django 5.2.4 on 2025-09-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0006_rename_name_worker_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="username",
            new_name="name",
        ),
    ]
