# Generated by Django 5.2.4 on 2026-04-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_rename_stripe_checkout_session_id_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='razorpay_order_id',
            new_name='stripe_checkout_session_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
    ]
