# Generated by Django 5.2.4

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("HomeApp", "0011_alter_userprofile_phone_alter_worker_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="time",
            new_name="time_slot",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=Q(status__in=["pending", "confirmed", "accepted"]),
                fields=("worker", "date", "time_slot"),
                name="unique_active_worker_booking_time_slot",
            ),
        ),
    ]
