import React, { useEffect, useState } from 'react';
import AdminLayout from '../components/AdminLayout';
import { adminFetch, readAdminError } from '../adminUtils';
import { API_ENDPOINTS } from '../../constants/api';

const empty = { worker_id: '', name: '', description: '', price: '100' };

const Services = () => {
  const [services, setServices] = useState([]); const [workers, setWorkers] = useState([]); const [search, setSearch] = useState(''); const [active, setActive] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null);
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); if (search) params.set('search', search); if (active) params.set('is_active', active); const [servicesResponse, workersResponse] = await Promise.all([adminFetch(`${API_ENDPOINTS.ADMIN_SERVICES}?${params}`), adminFetch(`${API_ENDPOINTS.ADMIN_WORKERS}?limit=100`)]); if (!servicesResponse.ok) throw new Error(await readAdminError(servicesResponse, 'Unable to load services')); const data = await servicesResponse.json(); setServices(data.services || []); if (workersResponse.ok) setWorkers((await workersResponse.json()).workers || []); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [search, active]);
  const save = async (event) => { event.preventDefault(); const url = editing ? API_ENDPOINTS.ADMIN_SERVICE(editing.id) : API_ENDPOINTS.ADMIN_SERVICES; const method = editing ? 'PATCH' : 'POST'; const response = await adminFetch(url, { method, body: JSON.stringify(form) }); if (!response.ok) { setError(await readAdminError(response)); return; } setForm(empty); setEditing(null); load(); };
  const remove = async (service) => { if (!window.confirm(`Delete ${service.service_name}?`)) return; const response = await adminFetch(API_ENDPOINTS.ADMIN_SERVICE(service.id), { method: 'DELETE' }); if (!response.ok) setError(await readAdminError(response)); else load(); };
  const toggle = async (service) => { const response = await adminFetch(`${API_ENDPOINTS.ADMIN_SERVICE(service.id)}toggle/`, { method: 'PATCH' }); if (!response.ok) setError(await readAdminError(response)); else load(); };
  const startEdit = (service) => { setEditing(service); setForm({ worker_id: service.worker_id, name: service.service_name, description: service.description || '', price: service.price }); };

  return <AdminLayout><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-600">Marketplace catalogue</p><h2 className="text-3xl font-bold text-slate-950">Services</h2><p className="mt-1 text-slate-500">Manage worker-provided services, pricing and availability.</p></div><div className="rounded-xl bg-white px-4 py-3 text-sm text-slate-500 ring-1 ring-slate-200">{services.length} services</div></div>
    <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_160px_auto]"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search service or worker" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-emerald-500" /><select value={active} onChange={(e) => setActive(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select><button onClick={() => { setEditing(null); setForm(empty); }} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">+ Add service</button></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-12 text-center text-sm text-slate-500">Loading services…</div> : services.length === 0 ? <div className="p-12 text-center text-sm text-slate-500">No services found.</div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Service</th><th className="px-5 py-4">Worker</th><th className="px-5 py-4">Price</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{services.map((service) => <tr key={service.id}><td className="px-5 py-4"><p className="font-semibold text-slate-800">{service.service_name}</p><p className="max-w-sm truncate text-xs text-slate-500">{service.description || 'No description'}</p></td><td className="px-5 py-4 text-slate-700">{service.worker_name}</td><td className="px-5 py-4 font-semibold text-slate-700">₹{service.price}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${service.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{service.is_active ? 'Active' : 'Inactive'}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => startEdit(service)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold">Edit</button><button onClick={() => toggle(service)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-emerald-700">{service.is_active ? 'Deactivate' : 'Activate'}</button><button onClick={() => remove(service)} className="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700">Delete</button></div></td></tr>)}</tbody></table></div>}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold text-slate-950">{editing ? 'Edit service' : 'Add service'}</h3><p className="text-xs text-slate-500">Every service belongs to a worker.</p></div>{editing && <button onClick={() => { setEditing(null); setForm(empty); }} className="text-sm text-slate-500">Clear</button>}</div><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><select required value={form.worker_id} onChange={(e) => setForm({ ...form, worker_id: e.target.value })} disabled={!!editing} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Select worker</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name} · {worker.category}</option>)}</select><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Service name" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Description" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><input required min="100" type="number" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} placeholder="Price" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><button className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white md:col-span-2">{editing ? 'Save service' : 'Create service'}</button></form></div>
  </div></AdminLayout>;
};

export default Services;
