import React, { useCallback, useEffect, useState } from 'react';
import AdminLayout from '../components/AdminLayout';
import { adminFetch, readAdminError } from '../adminUtils';
import { API_ENDPOINTS } from '../../constants/api';

const date = (value) => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

const UsersPage = () => {
  const [users, setUsers] = useState([]); const [pagination, setPagination] = useState({}); const [search, setSearch] = useState(''); const [active, setActive] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState({});

  const load = useCallback(async () => {
    setLoading(true); setError('');
    const params = new URLSearchParams({ page, limit: 12 }); if (search) params.set('search', search); if (active) params.set('is_active', active);
    try { const response = await adminFetch(`${API_ENDPOINTS.ADMIN_USERS}?${params}`); if (!response.ok) throw new Error(await readAdminError(response, 'Unable to load customers')); const data = await response.json(); setUsers(data.users || []); setPagination(data.pagination || {}); } catch (err) { setError(err.message); } finally { setLoading(false); }
  }, [page, search, active]);
  useEffect(() => { load(); }, [load]);

  const open = async (user) => { const response = await adminFetch(API_ENDPOINTS.ADMIN_USER(user.id)); if (response.ok) { const data = await response.json(); setSelected(data); setForm(data); setEditing(false); } };
  const toggle = async (user) => { if (!window.confirm(`${user.is_active ? 'Deactivate' : 'Activate'} ${user.username}?`)) return; const response = await adminFetch(API_ENDPOINTS.ADMIN_USER_STATUS(user.id), { method: 'PATCH' }); if (!response.ok) setError(await readAdminError(response)); else load(); };
  const save = async (event) => { event.preventDefault(); const response = await adminFetch(API_ENDPOINTS.ADMIN_USER(selected.id), { method: 'PATCH', body: JSON.stringify(form) }); if (!response.ok) setError(await readAdminError(response)); else { setSelected(await response.json()); setEditing(false); load(); } };

  return <AdminLayout><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-600">People</p><h2 className="text-3xl font-bold text-slate-950">Customers</h2><p className="mt-1 text-slate-500">Search, review and manage customer accounts.</p></div><div className="rounded-xl bg-white px-4 py-3 text-sm text-slate-500 ring-1 ring-slate-200">{pagination.total || 0} customers</div></div>
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search name, username or email" className="flex-1 rounded-xl border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-emerald-500" /><select value={active} onChange={(e) => { setActive(e.target.value); setPage(1); }} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-12 text-center text-sm text-slate-500">Loading customers…</div> : users.length === 0 ? <div className="p-12 text-center text-sm text-slate-500">No customers match these filters.</div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Contact</th><th className="px-5 py-4">Bookings</th><th className="px-5 py-4">Joined</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((user) => <tr key={user.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{user.full_name}</p><p className="text-xs text-slate-500">@{user.username}</p></td><td className="px-5 py-4"><p className="text-slate-700">{user.email || '—'}</p><p className="text-xs text-slate-500">{user.phone || 'No phone'}</p></td><td className="px-5 py-4 font-semibold text-slate-700">{user.total_bookings}</td><td className="px-5 py-4 text-slate-500">{date(user.date_joined)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${user.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{user.is_active ? 'Active' : 'Inactive'}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => open(user)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-100">Details</button><button onClick={() => toggle(user)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-50">{user.is_active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div>}</div>
    {pagination.pages > 1 && <div className="flex items-center justify-between text-sm text-slate-500"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button disabled={!pagination.has_previous} onClick={() => setPage(page - 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 disabled:opacity-40">Previous</button><button disabled={!pagination.has_next} onClick={() => setPage(page + 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 disabled:opacity-40">Next</button></div></div>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" onClick={() => setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-sm text-emerald-600">Customer #{selected.id}</p><h3 className="text-2xl font-bold text-slate-950">{selected.full_name}</h3></div><button onClick={() => setSelected(null)} className="text-2xl text-slate-400">×</button></div>{editing ? <form onSubmit={save} className="mt-6 space-y-4">{[['first_name','First name'],['last_name','Last name'],['email','Email'],['phone','Phone'],['city','City'],['address','Address']].map(([key,label]) => <label key={key} className="block text-sm font-medium text-slate-700">{label}<input value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-emerald-500" /></label>)}<div className="flex gap-2"><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save changes</button><button type="button" onClick={() => setEditing(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm">Cancel</button></div></form> : <><div className="mt-6 grid grid-cols-2 gap-3">{[['Email',selected.email],['Phone',selected.phone],['City',selected.city],['Joined',date(selected.date_joined)],['Bookings',selected.total_bookings],['Spent',`₹${selected.total_spent || 0}`]].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-800">{value || '—'}</p></div>)}</div><div className="mt-6 flex items-center justify-between"><h4 className="font-semibold">Booking history</h4><button onClick={() => setEditing(true)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Edit customer</button></div><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{(selected.bookings || []).map((booking) => <div key={booking.id} className="flex justify-between gap-3 p-3 text-sm"><div><p className="font-semibold">#{booking.id} · {booking.service_name}</p><p className="text-xs text-slate-500">{booking.worker_name} · {date(booking.scheduled_date)}</p></div><span className="capitalize text-slate-500">{booking.booking_status.replace('_',' ')}</span></div>)}</div></>}</aside></div>}
  </div></AdminLayout>;
};

export default UsersPage;
