import React, { useCallback, useEffect, useState } from 'react';
import AdminLayout from '../components/AdminLayout';
import { adminFetch, readAdminError } from '../adminUtils';
import { API_ENDPOINTS } from '../../constants/api';

const date = (value) => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const badge = { pending: 'bg-amber-50 text-amber-700', approved: 'bg-emerald-50 text-emerald-700', rejected: 'bg-rose-50 text-rose-700' };

const WorkersPage = () => {
  const [workers, setWorkers] = useState([]); const [pagination, setPagination] = useState({}); const [search, setSearch] = useState(''); const [verification, setVerification] = useState(''); const [active, setActive] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null);
  const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ page, limit: 12 }); if (search) params.set('search', search); if (verification) params.set('verification_status', verification); if (active) params.set('is_active', active); try { const response = await adminFetch(`${API_ENDPOINTS.ADMIN_WORKERS}?${params}`); if (!response.ok) throw new Error(await readAdminError(response, 'Unable to load workers')); const data = await response.json(); setWorkers(data.workers || []); setPagination(data.pagination || {}); } catch (err) { setError(err.message); } finally { setLoading(false); } }, [page, search, verification, active]);
  useEffect(() => { load(); }, [load]);
  const open = async (worker) => { const response = await adminFetch(API_ENDPOINTS.ADMIN_WORKER(worker.id)); if (response.ok) setSelected(await response.json()); };
  const verify = async (worker, verification_status) => { const label = verification_status === 'approved' ? 'approve' : 'reject'; if (!window.confirm(`Are you sure you want to ${label} ${worker.name}?`)) return; const response = await adminFetch(API_ENDPOINTS.ADMIN_WORKER_VERIFY(worker.id), { method: 'PATCH', body: JSON.stringify({ verification_status }) }); if (!response.ok) setError(await readAdminError(response)); else load(); };
  const toggle = async (worker) => { const response = await adminFetch(API_ENDPOINTS.ADMIN_WORKER_STATUS(worker.id), { method: 'PATCH' }); if (!response.ok) setError(await readAdminError(response)); else load(); };

  return <AdminLayout><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-600">Supply side</p><h2 className="text-3xl font-bold text-slate-950">Workers</h2><p className="mt-1 text-slate-500">Review provider applications and manage availability.</p></div><div className="rounded-xl bg-white px-4 py-3 text-sm text-slate-500 ring-1 ring-slate-200">{pagination.total || 0} workers</div></div>
    <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_180px_160px]"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search worker, username or email" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-emerald-500" /><select value={verification} onChange={(e) => { setVerification(e.target.value); setPage(1); }} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><option value="">All approvals</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><select value={active} onChange={(e) => { setActive(e.target.value); setPage(1); }} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><option value="">All activity</option><option value="true">Active</option><option value="false">Inactive</option></select></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-12 text-center text-sm text-slate-500">Loading workers…</div> : workers.length === 0 ? <div className="p-12 text-center text-sm text-slate-500">No workers match these filters.</div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Worker</th><th className="px-5 py-4">Profession</th><th className="px-5 py-4">Rating</th><th className="px-5 py-4">Approval</th><th className="px-5 py-4">Activity</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{workers.map((worker) => <tr key={worker.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{worker.name}</p><p className="text-xs text-slate-500">{worker.email || `@${worker.username}`}</p></td><td className="px-5 py-4"><p className="text-slate-700">{worker.category}</p><p className="text-xs text-slate-500">{worker.location || 'Location not set'}</p></td><td className="px-5 py-4 font-semibold text-slate-700">★ {worker.rating || '0.0'} <span className="text-xs font-normal text-slate-400">({worker.total_ratings})</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${badge[worker.verification_status] || 'bg-slate-100 text-slate-600'}`}>{worker.verification_status}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${worker.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{worker.is_active ? 'Active' : 'Inactive'}</span></td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button onClick={() => open(worker)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700">Details</button>{worker.verification_status !== 'approved' && <button onClick={() => verify(worker, 'approved')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Approve</button>}{worker.verification_status !== 'rejected' && <button onClick={() => verify(worker, 'rejected')} className="rounded-lg bg-rose-600 px-3 py-1.5 text-xs font-semibold text-white">Reject</button>}<button onClick={() => toggle(worker)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">{worker.is_active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div>}</div>
    {pagination.pages > 1 && <div className="flex items-center justify-between text-sm text-slate-500"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button disabled={!pagination.has_previous} onClick={() => setPage(page - 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 disabled:opacity-40">Previous</button><button disabled={!pagination.has_next} onClick={() => setPage(page + 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 disabled:opacity-40">Next</button></div></div>}
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" onClick={() => setSelected(null)}><aside className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-sm text-emerald-600">Worker #{selected.id}</p><h3 className="text-2xl font-bold text-slate-950">{selected.name}</h3><p className="text-sm text-slate-500">{selected.profession}</p></div><button onClick={() => setSelected(null)} className="text-2xl text-slate-400">×</button></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Approval</p><p className="mt-1 font-semibold capitalize">{selected.verification_status}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Rating</p><p className="mt-1 font-semibold">★ {selected.rating} ({selected.total_ratings})</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Joined</p><p className="mt-1 font-semibold">{date(selected.date_joined)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Bookings</p><p className="mt-1 font-semibold">{selected.total_bookings}</p></div></div><h4 className="mt-7 font-semibold">Services provided</h4><div className="mt-3 space-y-2">{(selected.services || []).map((service) => <div key={service.id} className="flex justify-between rounded-xl border border-slate-200 p-3 text-sm"><span>{service.service_name}</span><span className="font-semibold">₹{service.price}</span></div>)}</div><h4 className="mt-7 font-semibold">Booking history</h4><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{(selected.bookings || []).map((booking) => <div key={booking.id} className="flex justify-between gap-3 p-3 text-sm"><div><p className="font-semibold">#{booking.id} · {booking.service_name}</p><p className="text-xs text-slate-500">{booking.user_name} · {date(booking.scheduled_date)}</p></div><span className="capitalize text-slate-500">{booking.booking_status.replace('_',' ')}</span></div>)}</div></aside></div>}
  </div></AdminLayout>;
};

export default WorkersPage;
